name: test_better_t_stack

services:
  postgres:
    image: postgres
    container_name: test_better_t_stack-postgres
    environment:
      POSTGRES_DB: test_better_t_stack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - test_better_t_stack_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  test_better_t_stack_postgres_data: